project:
  type: website

website:
  title: "Nabila Parijat"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: Publications.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
